### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [navanchauhan/VaporwaveGenerator#2] opened 2020-03-31 10:03 UTC
Cannot find module named log zero, even after installing.

**Comment by navanchauhan** [comment] 2020-03-31 11:20
I have updated the requirements file

Simply try

`python3 -m pip install -r requirements.txt`
`python3 main.py`

If the issue still persists, please comment your log for running pip as well as running the main script

**Comment by ghost** [comment] 2020-03-31 11:22
Fixed it, but now I get this.

Traceback (most recent call last):                              File "main.py", line 168, in <module>                           gen_vapor(name, title)                                      File "main.py", line 152, in gen_vapor                          VaporSong.vaporize_song(filePath, title)                    File "/home/ubuntu/VaporwaveGenerator/src/VaporSong.py", line 166, in vaporize_song                                           bm = VaporSong.fetchbeats("beats/out.wav")                  File "/home/ubuntu/VaporwaveGenerator/src/VaporSong.py", line 53, in fetchbeats                                               beats = subprocess.check_output(["noah", "get-beats",src]).rstrip()                                                       File "/usr/lib/python3.6/subprocess.py", line 356, in check_output                                                            **kwargs).stdout                                            File "/usr/lib/python3.6/subprocess.py", line 423, in run       with Popen(*popenargs, **kwargs) as process:                File "/usr/lib/python3.6/subprocess.py", line 729, in __init__                                                                restore_signals, start_new_session)                         File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child                                                         raise child_exception_type(errno_num, err_msg, err_filename)                                                            FileNotFoundError: [Errno 2] No such file or directory: 'noah': 'noah'

**Comment by ghost** [comment] 2020-03-31 11:27
This is what I get when I run the program with python3 main.py -M -I https://m.youtube.com/watch?feature=youtu.be&v=X0WNQ3UYbJE

**Comment by navanchauhan** [comment] 2020-03-31 11:29
I understand what the issue is, 

please run 
`$ python3`
`>>> import os`
`>>> os.name `

I will fix the issue as soon as you send me this output, I will try to run this on another linux system

**Comment by ghost** [comment] 2020-03-31 11:31
Output is as follows:

'Posix'

**Comment by navanchauhan** [comment] 2020-03-31 11:31
Are you running this on macOS?

**Comment by ghost** [comment] 2020-03-31 11:31
No, Ubuntu.

**Comment by navanchauhan** [comment] 2020-03-31 11:32
Ahh, I understand where I went wrong, I am patching this in a minute

**Comment by ghost** [comment] 2020-03-31 11:32
Thanks

**Comment by navanchauhan** [comment] 2020-03-31 11:34
Fixed in #3 

`git pull` should fetch the changes

**Comment by ghost** [comment] 2020-03-31 11:35
Thank you, let me try now.

**Comment by navanchauhan** [comment] 2020-03-31 11:37
Also the input link might not work, try "https://youtu.be/X0WNQ3UYbJE" rather than "https://m.youtube.com/watch?feature=youtu.be&v=X0WNQ3UYbJE"

**Comment by ghost** [comment] 2020-03-31 11:38
Traceback (most recent call last):                              File "main.py", line 168, in <module>                           gen_vapor(name, title)                                      File "main.py", line 152, in gen_vapor                          VaporSong.vaporize_song(filePath, title)                    File "/home/ubuntu/VaporwaveGenerator/src/VaporSong.py", line 168, in vaporize_song                                           bm = VaporSong.fetchbeats("beats/out.wav")                  File "/home/ubuntu/VaporwaveGenerator/src/VaporSong.py", line 57, in fetchbeats                                               beats = subprocess.check_output(["get-beats",src]).rstrip()                                                               File "/usr/lib/python3.6/subprocess.py", line 356, in check_output                                                            **kwargs).stdout                                            File "/usr/lib/python3.6/subprocess.py", line 423, in run       with Popen(*popenargs, **kwargs) as process:                File "/usr/lib/python3.6/subprocess.py", line 729, in __init__                                                                restore_signals, start_new_session)                         File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child                                                         raise child_exception_type(errno_num, err_msg, err_filename)                                                            FileNotFoundError: [Errno 2] No such file or directory: 'get-beats': 'get-beats'

**Comment by ghost** [comment] 2020-03-31 11:40
> Also the input link might not work, try "https://youtu.be/X0WNQ3UYbJE" rather than "https://m.youtube.com/watch?feature=youtu.be&v=X0WNQ3UYbJE"

Tried that aswell, got this:

~/VaporwaveGenerator$ python3 main.py -M -i https://youtu.be/X0WNQ3UYbJ                             usage: main.py [-h] [-M] [-P] [-V] [-v] [-i INPUT] [-o OUTPUT]                                                              | V A P O R W A V E || G E N E R A T O R |                                                                                  optional arguments:                                             -h, --help            show this help message and exit         -M, --music           generate v a p o r w a v e music        -P, --picture         generate VHS Style image                -V, --video           VHS Style Video                         -v, --version         show program version                    -i INPUT, --input INPUT                                       -o OUTPUT, --output OUTPUT                                                          Output for specifying output video    [I 200331 11:39:15 main:111] Query was a YouTube URL.         WARNING: Falling back on generic information extractor.       ERROR: Unsupported URL: https://www.youtube.com/watch?v=X0WNQ3UYbJ&feature=youtu.be                                         Traceback (most recent call last):                              File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info                     ie_result = ie.extract(url)                                 File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract                   ie_result = self._real_extract(url)                         File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3352, in _real_extract           raise UnsupportedError(url)                               youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/watch?v=X0WNQ3UYbJ&feature=youtu.be                                                                           During handling of the above exception, another exception occurred:                                                                                                                       Traceback (most recent call last):                              File "main.py", line 167, in <module>                           name, title = download_file(query)                          File "main.py", line 113, in download_file                      info = youtube_dl.YoutubeDL(ydl_opts).extract_info(url,download = False)                                                  File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info                     return self.process_ie_result(ie_result, download, extra_info)                                                            File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 870, in process_ie_result                extra_info=extra_info)                                      File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 820, in extract_info                     self.report_error(compat_str(e), e.format_traceback())      File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error                     self.trouble(error_message, tb)                             File "/home/ubuntu/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble                          raise DownloadError(message, exc_info)                    youtube_dl.utils.DownloadError: ERROR: Unsupported URL: https://www.youtube.com/watch?v=X0WNQ3UYbJ&feature=youtu.be         [1]+  Exit 1                  python3 main.py -M -i https://m.youtube.com/watch?feature=youtu.be

**Comment by navanchauhan** [comment] 2020-03-31 11:43
what happens when you run 

`chmod +x get-beats`

`./get-beats`

**Comment by ghost** [comment] 2020-03-31 11:45
~/VaporwaveGenerator$ ./get-beats     AUBIO-TESTS ERROR: not enough arguments                       read a wave file as a mono vector                             usage: ./get-beats <source_path> [samplerate] [win_size] [hop_size]

**Comment by navanchauhan** [comment] 2020-03-31 11:50
This implies there is nothing wrong with the compiled binary,

can you try changing `get-beats` to `./get-beats` ( Line 57, src/VaporSong.py )

**Comment by ghost** [comment] 2020-03-31 11:51
OK, sure

**Comment by navanchauhan** [comment] 2020-03-31 12:06
Did this fix it?

**Comment by ghost** [comment] 2020-03-31 12:08
Yes I suggest you put the chmod command in the readme md and modify the python file like I did, thanks for your help

**Comment by navanchauhan** [comment] 2020-03-31 12:09
Yes, I will do that 👍

**Closed as completed by navanchauhan** 2020-03-31 12:09 UTC
